### PR TITLE
add assert for deleting ArchMemory of currentThread

### PR DESCRIPTION
**Pull request by v4m1n**

### CODE REVIEW

**Comment by misc0110** [comment]
shouldn't there be a == instead of = in Line 21?

**Comment by v4m1n** [comment]
> shouldn't there be a == instead of = in Line 121?

that's intentional. Since the loader is mostly deleted at that point we have to do something to avoid printing the user backtrace during the assert otherwise we would get a null pointer dereference during the assert.

**Comment by dgruss** [comment]
that's ugly though... maybe we can find something more beautiful code-wise...

**Comment by v4m1n** [comment]
that should fix quite a few asserts

**Pull request merged**
