### PR TITLE
Use getLoader() interface function instead of directly accessing Thread->loader_

### PR DESCRIPTION
**Pull request by Woazboat**

### CODE REVIEW

**Comment by dgruss** [comment]
i don't see the advantage of this change

**Comment by fkirc** [comment]
I think the getLoader is supposed to make necessary changes in assignment 1 easier  (changing the getLoader function once instead of changing multiple places). Still, it is not a must have patch

**Comment by dgruss** [comment]
i don't think it's necessary

**Comment by Woazboat** [comment]
> I think the getLoader is supposed to make necessary changes in assignment 1 easier (changing the getLoader function once instead of changing multiple places). Still, it is not a must have patch

Yes, that was the idea behind this. The direct dependency on Thread->loader_ in a lot of different places can cause some headaches when students try to change it.

**Pull request closed without merging**
