### PR TITLE
Fix atomic_add for u/int64 on x86_64

### PR DESCRIPTION
**Pull request by Woazboat**
Didn't actually add 64 bit integers previously, only truncated 32 bit integers.

### CODE REVIEW

**Comment by dgruss** [comment]
i'm not sure sync_fetch_and_add can be trusted in a -nostartfiles etc. scenario, i've seen some of the intrinsics generate code that relied on kernel functionality that's obviously not there.

**Comment by dgruss** [comment]
we should probably stick to inline assembly

**Comment by dgruss** [comment]
I think the problem came from not using a cross compiler. this is fine most of the time. but anything you rely on can make incorrect assumptions. the problem i think was on arm when using gcc-arm-linux-gnueabi instead of gcc-arm-none-gnueabi

so, let's be careful with this and rather stick to inline assembly? shall we close this one?

**Comment by Woazboat** [comment]
What about the other atomic functions? All other atomic functions on x86 already use buiiltins.
64bit atomic_add on x86_32 also uses `__sync_fetch_and_add(&value,increment)`. I just copied that from there.

**Comment by dgruss** [comment]
i don't trust them either ;) i think they could break any time?

**Comment by Ferdi265** [comment]
I can confirm that some `__sync` and `__atomic` builtins break at least on arm_verdex and arm_icp (<= armv6), since those are functions from `libgcc.a` on those systems.

Though I still think that using them on architectures where we know that it generates no calls to `libgcc.a` and providing alternate implementations on other architectures is acceptable.

I think it is also worth pointing out that `ustl` uses these functions for its implementation of `atomic<T>` and therefore in `unique_ptr<T>` and `shared_ptr<T>`.

It is probably reasonable to expand the implementations of atomic functions in `ArchThreads` to the set defined by the `__sync` or `__atomic` builtins and then call those from `ustl::atomic<T>`.

**Comment by dgruss** [comment]
The problem is, you never know when it changes in upstream.
We're talking about (one line) asm snippets that all students should be able to understand and actually it's part of the OS class to fully understand them. Hiding them from the students by switching to a (one line) call to an external function, which might break any time, does not sound like the most reasonable way to go.

**Comment by Ferdi265** [comment]
a PR that fixes this with a _correct_ asm statement would probably be more in line with the idea of the OS class, right?

**Comment by dgruss** [comment]
Yes

**Pull request closed without merging**
