### PR TITLE
Updated debug.h

### PR DESCRIPTION
**Pull request by notaloveletter**
changed the debug message BACKTRACE from Ansi_Red to Ansi_Cyan.

### CODE REVIEW

**Comment by Woazboat** [comment]
Hi, could you squash the two commits into one 
(`git rebase -i HEAD~2` -> change the second commit from `pick` to `squash` -> `git rebase --continue` [may not be required])

**Comment by notaloveletter** [comment]
Hi, I hope it worked now, I am not sure about it ... sorry

**Comment by Woazboat** [comment]
Looking good. Thanks^^

**Comment by dgruss** [comment]
This is worth 0.5 points for the exercises. I'll merge it after the first deadline I think

**Comment by notaloveletter** [comment]
Perfect thanks.

**Pull request merged**
