### PR TITLE
 Reload cr3 when changing address space of currentThread 

### PR DESCRIPTION
**Pull request by Woazboat**

### CODE REVIEW

**Comment by dgruss** [comment]
why are there so many commits in this pull request?

**Comment by Woazboat** [comment]
Same reason as https://github.com/IAIK/sweb/pull/196#issuecomment-438512125

**Comment by dgruss** [comment]
can we get a cleaner version?

**Comment by Woazboat** [comment]
> can we get a cleaner version?

also done

**Pull request merged**
