### PR TITLE
Fix add-debug build again

### PR DESCRIPTION
**Pull request by mickdermack**
This fixes an issue with @Woazboat's PR #148 which missed a dependency on dwarf++.

### CODE REVIEW

**Comment by mickdermack** [comment]
Ah. Wrong branch.

**Comment by dgruss** [comment]
master branch is fine currently, we're in the february merge window where things can go into the master branch

**Comment by dgruss** [comment]
is the copy not necessary?

**Comment by mickdermack** [comment]
As far as I can tell, no. This copies a file which is already copied [here](https://github.com/mickdermack/sweb/blob/0f5818e03924996b097bfe7942b3a5e3b36fd6f7/utils/add-debug/elf/CMakeLists.txt#L10).

**Comment by Woazboat** [comment]
It relies on the fact that cmake will put both folders next to each other in the same subdirectory. I'm not sure if that's always a valid assumption to make, so maybe an explicit copy would be better? The whole situation is rather suboptimal in any case. Either making assumptions about the behavior of cmake or copying files into some potentially unknown directory outside of the current build path...

**Comment by mickdermack** [comment]
If they are not next to each other the build will fail anyway, because dwarf++ includes `../elf/to_hex.hh`, which is why I opened this PR. I don't think we lose anything by assuming this in yet another place.

**Comment by Woazboat** [comment]
I meant copying the whole elf folder for the dwarf build instead of only the enum-print.py file.

**Comment by dgruss** [comment]
Generally I would expect building SWEB like described in the Wiki. That is:

git clone git@github.com:IAIK/sweb.git ~/sweb
mkdir -p /tmp/sweb
cd /tmp/sweb
cmake ~/sweb
make -j
make qemu

So, we're building out of source, and ideally in a tmpfs mounted folder to not scrub the disk too much.

In source builds should not work, I had added messages into the cmake files some while ago. Not sure if they still work.

**Comment by mickdermack** [comment]
Yep, that's also the setup I've been working with.

Maybe a nicer option would be to add `target_include_directories(dwarf++ PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")` so `#include "../elf/*"` will fall back to `srcdir/utils/add-debug/dwarf/../elf/*` if it can't be found in the current directory. What do you think, @Woazboat?

**Comment by dgruss** [comment]
> Maybe a nicer option would be to add |target_include_directories(dwarf++ PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")| so
> |#include "../elf/*"| will fall back to |srcdir/utils/add-debug/dwarf/../elf/*| if it can't be found in the current
> directory. What do you think, @Woazboat <https://github.com/woazboat>?

Sounds much cleaner than copying source files to the bin dir....

**Comment by Woazboat** [comment]
That sounds like the best solution to fix the missing include problem for the dwarf++ build. Copying the files to the build dir is however still required for generating the `to_string.cc` file out of source.

**Comment by mickdermack** [comment]
Ah, right. I guess the best solution would really be to pull the logic for generating `to_string.cc` out of the Makefile since it was _really_ not written with out-of-source builds in mind.

**Comment by mickdermack** [comment]
There we go. Please have a look.

**Comment by Woazboat** [comment]
Yes, that works. The Makefile isn't used for anything else if I'm not mistaken, so maybe it could be removed.

**Comment by mickdermack** [comment]
Done

**Comment by dgruss** [comment]
sounds good

**Pull request merged**
