### PR TITLE
Various build fixes and cleanups #2

### PR DESCRIPTION
**Pull request by mickdermack**
The second PR in this series.

fd6db3b also removes a dependency on make, i.e. you can now build sweb using ninja if you want to, using `cmake -G Ninja /path/to/sweb && ninja`.
Side effects may include: Colorless GCC error messages and a speedup from 7 seconds to 5 seconds (on my system, vs. `make -j8`).

### CODE REVIEW

**Comment by dgruss** [comment]
pull request needs clean up.... loads of unnecessary mode changes..

**Comment by dgruss** [comment]
not sure the mode changes make sense, unless there's a way to ignore mode changes entirely we'll get them back in as people using windows commit changes...

**Comment by mickdermack** [comment]
I just tested, and the latest version of Git for Windows doesn't seem to set the executable bit on new files. Do you know of any specific configurations that cause this?

The last time a file was wrongly committed as executable was in 2016 (eff920ddd96a80d6778defa33fde66314455823e) and before that, all the way back in 2012 (daabc78e73c58e61355bbd29324395fab8f832a7).

Given the amount of work that has been done on SWEB in the meantime, I don't think that Git on Windows will cause problems. Nevertheless I'd be willing to drop e225947 if so requested.

**Comment by dgruss** [comment]
Fair point, we can give it a try.

**Pull request merged**
