### PR TITLE
Fix travis CI build environment for aarch64 + add gcc 10

### PR DESCRIPTION
**Pull request by Woazboat**

### CODE REVIEW

**Comment by dgruss** [comment]
does this fix the CI problems?

**Comment by Woazboat** [comment]
Not yet unfortunately, but I need to create a PR to be able to see the CI result. This is why this PR is still marked as a draft. (The previous one should also have been marked as a draft but unfortunately I forgot to do that)

**Comment by Woazboat** [comment]
Looks like the aarch64 qemu version used by the CI is simply too old to support the raspberry pi 3

**Comment by Woazboat** [comment]
This should now be in a working state and can be merged

**Comment by Woazboat** [comment]
Only compilation is tested for aarch64/raspi3 since the shipped qemu version in the travis CI is too old and does not yet support the raspi3 (and changing to a newer distro didn't work for some reason)

**Pull request merged**
